---
title: "Project NFP - Final Report"
author: "Sam Choi, Eric Xu"
date: "4/17/2018"
output:
  html_document:
      fig_height: 3
      fig_width: 5
      keep_md: true
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DataComputing)
library(astsa)
#setwd("~/Dropbox/Berkeley/stat153/NFP-TSA/")
```

### Introduction

The Non Farm Payroll (NFP) Report is a monthly government report tracking the number of payrolls in the U.S., excluding farm workers, private household employees, and non-profit organization employees. It is collected and reported by the the U.S. Bureau of Labor Statistics (BLS), and is an influential economic indicator used to analyze the state of the labor market. 

The release of monthly NFP Reports has significant ramifications for economic policy makers and market participants. Thus, it is imperative for both economists and traders to have a general forecast of the next month's NFP Report in order to prepare for the volatility that ensues with the release of the report. 

The monthly data is collected by the BLS as a component of the Current Employment Statistics (CES) survey. About a third of all NFP workers are surveyed, and the value reported is the result of additional extrapolation and adjustment.

The objective of this analysis is twofold: To determine the extent to which seasonal and non-seasonal trends can be captured using techniques in univariate time series analysis, and to accurately forecast future NFP Reports.


### Data Analysis
- EDA
- Model Building (ARIMA, Spectral)
- Forecasting

##### Data
- univariate
- regularly spaced
- not too many outliers
- have ~100 observations
- source

### Conclusion
- Key Findings




